"use client";

import { useState } from "react";
import type { CSSProperties } from "react";

export default function AIProductGeneratorPage() {
  const [productName, setProductName] = useState("");
  const [category, setCategory] = useState("");
  const [country, setCountry] = useState("");

  const [result, setResult] = useState<any>(null);

  const generate = () => {
    setResult({
      title: `${productName} Premium Export Quality`,
      description: `${productName} is manufactured according to international quality standards and supplied globally for importers, distributors and wholesalers.`,
      keywords: `${productName}, exporter, supplier, wholesale, ${country}`,
      hsCode: "Generated by HXN AI",
      moq: "100 Units",
      packaging: "Export Standard Packaging",
      markets: "UAE, USA, UK, Germany, Saudi Arabia",
      specifications: [
        "Premium Quality",
        "Export Ready",
        "Global Standards",
        "Bulk Supply Available",
      ],
    });
  };

  return (
    <main style={styles.page}>
      <div style={styles.hero}>
        <div style={styles.badge}>HXN AI PRODUCT ENGINE</div>

        <h1 style={styles.title}>
          Product Listing
          <br />
          Generator
        </h1>

        <div style={styles.card}>
          <input
            style={styles.input}
            placeholder="Product Name"
            value={productName}
            onChange={(e) => setProductName(e.target.value)}
          />

          <input
            style={styles.input}
            placeholder="Category"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          />

          <input
            style={styles.input}
            placeholder="Country"
            value={country}
            onChange={(e) => setCountry(e.target.value)}
          />

          <button style={styles.button} onClick={generate}>
            Generate Product Listing
          </button>
        </div>

        {result && (
          <div style={styles.result}>
            <h2>{result.title}</h2>

            <p>{result.description}</p>

            <p>
              <strong>HS Code:</strong> {result.hsCode}
            </p>

            <p>
              <strong>MOQ:</strong> {result.moq}
            </p>

            <p>
              <strong>Packaging:</strong> {result.packaging}
            </p>

            <p>
              <strong>Target Markets:</strong> {result.markets}
            </p>

            <p>
              <strong>SEO Keywords:</strong> {result.keywords}
            </p>

            <ul>
              {result.specifications.map((item: string) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </main>
  );
}

const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background:
      "radial-gradient(circle at top,#16213f 0%,#07111f 45%,#020617 100%)",
    padding: 40,
    color: "#fff",
  },

  hero: {
    maxWidth: 1000,
    margin: "0 auto",
  },

  badge: {
    display: "inline-block",
    padding: "10px 20px",
    borderRadius: 999,
    background: "#0f172a",
    color: "#7dd3fc",
    marginBottom: 25,
    fontWeight: 900,
  },

  title: {
    fontSize: "clamp(50px,8vw,90px)",
    fontWeight: 950,
    lineHeight: 0.95,
  },

  card: {
    background: "#fff",
    color: "#000",
    padding: 30,
    borderRadius: 30,
    marginTop: 30,
  },

  input: {
    width: "100%",
    height: 60,
    marginBottom: 15,
    borderRadius: 15,
    border: "1px solid #ccc",
    padding: "0 15px",
  },

  button: {
    width: "100%",
    height: 60,
    border: "none",
    borderRadius: 15,
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
  },

  result: {
    marginTop: 30,
    padding: 30,
    borderRadius: 30,
    background: "rgba(255,255,255,.08)",
  },
};