"use client";

import { useState } from "react";
import type { CSSProperties } from "react";

export default function AICatalogueGenerator() {
  const [company, setCompany] = useState("");
  const [products, setProducts] = useState("");
  const [result, setResult] = useState("");

  const generateCatalogue = () => {
    setResult(`
${company}

GLOBAL EXPORT CATALOGUE

Products:
${products}

Why Choose Us
• Premium Quality
• Export Ready
• International Standards
• Global Logistics Support

Generated by HXN AI
`);
  };

  return (
    <main style={styles.page}>
      <h1 style={styles.title}>HXN AI Catalogue Generator</h1>

      <div style={styles.card}>
        <input
          style={styles.input}
          placeholder="Company Name"
          value={company}
          onChange={(e) => setCompany(e.target.value)}
        />

        <textarea
          style={styles.textarea}
          placeholder="Products"
          value={products}
          onChange={(e) => setProducts(e.target.value)}
        />

        <button style={styles.button} onClick={generateCatalogue}>
          Generate Catalogue
        </button>
      </div>

      {result && (
        <div style={styles.result}>
          <pre>{result}</pre>
        </div>
      )}
    </main>
  );
}

const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background:
      "radial-gradient(circle at top,#16213f 0%,#07111f 45%,#020617 100%)",
    color: "#fff",
    padding: 40,
  },

  title: {
    fontSize: 60,
    fontWeight: 900,
  },

  card: {
    background: "#fff",
    color: "#000",
    borderRadius: 30,
    padding: 30,
  },

  input: {
    width: "100%",
    height: 60,
    marginBottom: 15,
    borderRadius: 15,
    padding: 15,
  },

  textarea: {
    width: "100%",
    minHeight: 150,
    marginBottom: 15,
    borderRadius: 15,
    padding: 15,
  },

  button: {
    width: "100%",
    height: 60,
    border: "none",
    borderRadius: 15,
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
  },

  result: {
    marginTop: 30,
    background: "rgba(255,255,255,.08)",
    padding: 30,
    borderRadius: 20,
  },
};