"use client";

import { useState } from "react";
import type { CSSProperties } from "react";

export default function SellerRFQAssistant() {
  const [product, setProduct] = useState("");
  const [quantity, setQuantity] = useState("");
  const [price, setPrice] = useState("");
  const [result, setResult] = useState("");

  const generateRFQ = () => {
    setResult(`
QUOTATION GENERATED BY HXN AI

Product:
${product}

Quantity:
${quantity}

Unit Price:
${price}

Trade Terms:
FOB / CIF Available

Payment Terms:
TT / LC Accepted

Lead Time:
15 - 30 Days

Packaging:
Export Standard Packaging

Supplier Message:
Thank you for your interest. We are pleased to offer this quotation and look forward to establishing a long-term business relationship.

Generated by HXN AI
`);
  };

  return (
    <main style={styles.page}>
      <div style={styles.hero}>
        <div style={styles.badge}>HXN SELLER RFQ ASSISTANT</div>

        <h1 style={styles.title}>
          RFQ
          <br />
          Assistant
        </h1>

        <p style={styles.subtitle}>
          Generate professional quotations, RFQ responses and buyer proposals instantly.
        </p>

        <div style={styles.card}>
          <input
            style={styles.input}
            placeholder="Product"
            value={product}
            onChange={(e) => setProduct(e.target.value)}
          />

          <input
            style={styles.input}
            placeholder="Quantity"
            value={quantity}
            onChange={(e) => setQuantity(e.target.value)}
          />

          <input
            style={styles.input}
            placeholder="Unit Price"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
          />

          <button style={styles.button} onClick={generateRFQ}>
            Generate RFQ Response
          </button>
        </div>

        {result && (
          <div style={styles.result}>
            <pre>{result}</pre>
          </div>
        )}
      </div>
    </main>
  );
}

const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background:
      "radial-gradient(circle at top,#16213f 0%,#07111f 45%,#020617 100%)",
    color: "#fff",
    padding: 40,
  },

  hero: {
    maxWidth: 1000,
    margin: "0 auto",
  },

  badge: {
    display: "inline-flex",
    padding: "10px 20px",
    borderRadius: 999,
    background: "#0f172a",
    color: "#7dd3fc",
    fontWeight: 900,
    marginBottom: 20,
  },

  title: {
    fontSize: "clamp(50px,8vw,90px)",
    fontWeight: 950,
    lineHeight: 0.95,
  },

  subtitle: {
    color: "#dbeafe",
    marginTop: 20,
    marginBottom: 30,
  },

  card: {
    background: "#fff",
    padding: 30,
    borderRadius: 30,
  },

  input: {
    width: "100%",
    height: 60,
    marginBottom: 15,
    borderRadius: 15,
    border: "1px solid #ccc",
    padding: "0 15px",
  },

  button: {
    width: "100%",
    height: 60,
    border: "none",
    borderRadius: 15,
    background: "#2563eb",
    color: "#fff",
    fontWeight: 900,
    cursor: "pointer",
  },

  result: {
    marginTop: 30,
    background: "rgba(255,255,255,.08)",
    padding: 25,
    borderRadius: 25,
  },
};